spring:
  application:
    name: auth
  config:
    import: optional:file:.env.properties
  profiles:
    active: dev
  #  config:
  #    import: "configserver:http://localhost:18080"

server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}