spring:
  application:
    name: auth
  profiles:
    active: dev
#  config:
#    import: "configserver:http://localhost:18080"

server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

message: "default message" # config server? ???? ?? ?

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh