spring:
  application:
    name: auth
  profiles:
    active: dev
  #  config:
  #    import: "configserver:http://localhost:18080"
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh